services:
    mariadb:
        image: mariadb:latest
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: dolibarr
        volumes:
            - ./database:/var/lib/mysql
        networks:
            dolibarr-net:
                ipv4_address: 172.200.0.2

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        depends_on:
            - mariadb
        environment:
            PMA_HOST: mariadb
            PMA_PORT: 3306
            PMA_ARBITRARY: 1
        ports:
            - ${DB_MPORT}:80
        networks:
            dolibarr-net:
                ipv4_address: 172.200.0.3

    php:
        build:
            context: .
            dockerfile: Dockerfile.php
        volumes:
            - ./dolibarr:/var/www/html
        networks:
            dolibarr-net:
                ipv4_address: 172.200.0.4

    nginx:
        build:
            context: .
            dockerfile: Dockerfile.nginx
        ports:
            - ${WEB_PORT}:80
        volumes:
            - ./dolibarr:/var/www/html
        depends_on:
            - php
        networks:
            dolibarr-net:
                ipv4_address: 172.200.0.5

networks:
    dolibarr-net:
        driver: bridge
        ipam:
            config:
                - subnet: 172.200.0.0/29
